import {
  SignInButton,
  SignOutButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { NAVBAR_HEIGHT } from "~/constants/styles";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.problems.getAll.useQuery();

  const [bgDegree, setBgDegree] = useState(90);

  function easeInOutQuad(t: number, b: number, c: number, d: number) {
    t /= d / 2;
    if (t < 1) return (c / 2) * t * t + b;
    t--;
    return (-c / 2) * (t * (t - 2) - 1) + b;
  }

  useEffect(() => {
    const duration = 1250; // Duration in ms
    const start = Date.now();

    const animation = setInterval(() => {
      const now = Date.now();
      const elapsed = now - start;

      if (elapsed >= duration) {
        clearInterval(animation);
        setBgDegree(90); // Explicitly set to 450 degrees when animation ends
      } else {
        const degreeChange = easeInOutQuad(elapsed, 0, 360, duration);
        setBgDegree(90 + degreeChange);
      }
    }, 5); // Update every 20ms for smoother animation

    return () => clearInterval(animation);
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="flex min-h-screen flex-col items-center justify-center"
        style={{
          background: `conic-gradient(from ${bgDegree}deg at 7.5% ${NAVBAR_HEIGHT}, #ffb56b, #f3915e, #d5424b, #ae2474, #7a0f86, #350368, #211b29)`,
        }}
      >
        <div id="spacer" className="h-16" />
        <div id="container" className="h-screen w-full">
          <div className="mx-auto h-full w-full grow bg-white md:max-w-[888px]">
            <SignedIn>
              <SignOutButton>
                <button className="btn">Sign out</button>
              </SignOutButton>
            </SignedIn>
            <SignedOut>
              <SignInButton mode="modal">
                <button className="btn">Sign in</button>
              </SignInButton>
            </SignedOut>
            <div className="rounded-sm bg-[#e3e0cd]">
              {data?.map((problem) => (
                <div key={problem.id}>{problem.title}</div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
